CREATE TABLE Fornecedores (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Nome NVARCHAR(100) NOT NULL,
    CNPJ NVARCHAR(18) UNIQUE NOT NULL,
    Telefone NVARCHAR(20),
    Email NVARCHAR(100),
    Endereco NVARCHAR(255)
);