//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Fornecedores : INotifyPropertyChanged
    {
        private int iD;
        private string nome;
        private string cNPJ;
        private string telefone;
        private string email;
        private string endereco;

        public int ID
        {
            get => iD; set
            {
                iD = value;
                {
                    iD = value;
                    OnPropertyChanged(nameof(ID));
                }
            }
        }
        public string Nome
        {
            get => nome; set
            {
                nome = value;

                {
                    nome = value;
                    OnPropertyChanged(nameof(nome));
                }
            }
        }



        public string CNPJ
        {
            get => cNPJ; set
            {
                cNPJ = value;

                {
                    cNPJ = value;
                    OnPropertyChanged(nameof(cNPJ));
                }
            }
        }

        public string Telefone
        {
            get => telefone; set
            {
                telefone = value;

                {
                    telefone = value;
                    OnPropertyChanged(nameof(telefone));
                }
            }
        }

        public string Email
        {
            get => email; set
            {
                email = value;

                email = value;
                OnPropertyChanged(nameof(email));
            }
        }
        public string Endereco
        {
            get => endereco; set
            {
                endereco = value;

                endereco = value;
                OnPropertyChanged(nameof(endereco));
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
